import {
  BadgePlus,
  Building2,
  Boxes,
  Calculator,
  ClipboardList,
  CreditCard,
  Gauge,
  GitBranch,
  Handshake,
  Landmark,
  Mail,
  SquareActivity,
  UserCircle,
  UserRoundCog,
  Wrench,
} from "lucide-react";
import { PERMISSIONS } from "@/utils/permissions";

export const navigation = [
  {
    id: "dashboard",
    label: "Dashboard",
    path: "/dashboard",
    icon: Gauge,
    permissions: [
      PERMISSIONS.REPAIR_INTAKE,
      PERMISSIONS.REPAIR_JOBS_VIEW,
      PERMISSIONS.REPAIR_WORK,
      PERMISSIONS.INVENTORY_VIEW,
      PERMISSIONS.BILLING_VIEW,
      PERMISSIONS.REPORTS_VIEW,
      PERMISSIONS.BRANCH_VIEW,
      PERMISSIONS.STAFF_VIEW,
      PERMISSIONS.SUBSCRIPTION_MANAGE,
    ],
    category: "home",
  },
  {
    id: "repair-intake",
    label: "Repair Intake",
    path: "/repair/new",
    icon: BadgePlus,
    permissions: [PERMISSIONS.REPAIR_INTAKE],
    category: "repairs",
  },
  {
    id: "repair-work",
    label: "Technician Work",
    path: "/technician/repairs",
    icon: Wrench,
    permissions: [PERMISSIONS.REPAIR_WORK],
    category: "repairs",
  },
  {
    id: "repair-jobs",
    label: "Technician Report",
    path: "/repair",
    icon: ClipboardList,
    permissions: [PERMISSIONS.REPAIR_JOBS_VIEW],
    category: "repairs",
  },
  {
    id: "inventory",
    label: "Inventory",
    path: "/inventory",
    icon: Boxes,
    permissions: [PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_MANAGE, PERMISSIONS.INVENTORY_CONSUME],
    category: "more",
  },
  {
    id: "billing",
    label: "Billing",
    path: "/billing",
    icon: CreditCard,
    permissions: [PERMISSIONS.BILLING_VIEW, PERMISSIONS.BILLING_CREATE, PERMISSIONS.PAYMENT_COLLECT],
    category: "more",
  },
  {
    id: "handover",
    label: "Handover",
    path: "/handover",
    icon: Handshake,
    permissions: [PERMISSIONS.HANDOVER_VIEW, PERMISSIONS.HANDOVER_MANAGE],
    category: "more",
  },
  {
    id: "branches",
    label: "Branches",
    path: "/branches",
    icon: GitBranch,
    permissions: [PERMISSIONS.BRANCH_MANAGE],
    category: "business",
  },
  {
    id: "staff",
    label: "Staff",
    path: "/staff",
    icon: UserRoundCog,
    permissions: [PERMISSIONS.STAFF_VIEW, PERMISSIONS.STAFF_MANAGE],
    category: "team",
  },
  {
    id: "profile",
    label: "Profile",
    path: "/business",
    icon: UserCircle,
    permissions: [PERMISSIONS.BUSINESS_MANAGE, PERMISSIONS.SETTINGS_MANAGE],
    category: "business",
  },
  {
    id: "subscription",
    label: "Subscription",
    path: "/subscription",
    icon: CreditCard,
    permissions: [PERMISSIONS.SUBSCRIPTION_MANAGE],
    category: "business",
  },
  {
    id: "platform-dashboard",
    label: "Platform Dashboard",
    path: "/super-admin/dashboard",
    icon: SquareActivity,
    permissions: [PERMISSIONS.SUPER_ADMIN_MANAGE],
    category: "home",
  },
  {
    id: "platform-businesses",
    label: "Businesses",
    path: "/super-admin/businesses",
    icon: Landmark,
    permissions: [PERMISSIONS.SUPER_ADMIN_MANAGE],
    category: "business",
  },
  {
    id: "platform-inquiries",
    label: "Inquiries",
    path: "/super-admin/contacts",
    icon: Mail,
    permissions: [PERMISSIONS.SUPER_ADMIN_MANAGE],
    category: "more",
  },
];
